#!/bin/sh
#
# @name Gazebo teTra_mk-7_EM2
#
# @type Quadrotor
#

. ${R}etc/init.d/rc.mc_defaults

PX4_SIMULATOR=${PX4_SIMULATOR:=gz}
PX4_GZ_WORLD=${PX4_GZ_WORLD:=default}
PX4_SIM_MODEL=${PX4_SIM_MODEL:=teTra_mk-7_EM2}

param set-default SIM_GZ_EN 1

param set-default CA_AIRFRAME 22001
param set-default CA_ROTOR_COUNT 13

# Lift rotors (temporary example layout)
param set-default CA_ROTOR0_PX   0.13
param set-default CA_ROTOR0_PY   0.22
param set-default CA_ROTOR0_KM   0.05

param set-default CA_ROTOR1_PX  -0.13
param set-default CA_ROTOR1_PY  -0.20
param set-default CA_ROTOR1_KM   0.05

param set-default CA_ROTOR2_PX   0.13
param set-default CA_ROTOR2_PY  -0.22
param set-default CA_ROTOR2_KM  -0.05

param set-default CA_ROTOR3_PX  -0.13
param set-default CA_ROTOR3_PY   0.20
param set-default CA_ROTOR3_KM  -0.05

param set-default CA_ROTOR4_PX   0.30
param set-default CA_ROTOR4_PY   0.30
param set-default CA_ROTOR4_KM   0.05

param set-default CA_ROTOR5_PX  -0.30
param set-default CA_ROTOR5_PY   0.30
param set-default CA_ROTOR5_KM  -0.05

param set-default CA_ROTOR6_PX   0.30
param set-default CA_ROTOR6_PY  -0.30
param set-default CA_ROTOR6_KM  -0.05

param set-default CA_ROTOR7_PX  -0.30
param set-default CA_ROTOR7_PY  -0.30
param set-default CA_ROTOR7_KM   0.05

param set-default CA_ROTOR8_PX   0.45
param set-default CA_ROTOR8_PY   0.15
param set-default CA_ROTOR8_KM   0.05

param set-default CA_ROTOR9_PX  -0.45
param set-default CA_ROTOR9_PY   0.15
param set-default CA_ROTOR9_KM  -0.05

param set-default CA_ROTOR10_PX  0.45
param set-default CA_ROTOR10_PY -0.15
param set-default CA_ROTOR10_KM -0.05

param set-default CA_ROTOR11_PX -0.45
param set-default CA_ROTOR11_PY -0.15
param set-default CA_ROTOR11_KM  0.05

# Cruise prop (temporary example; forward prop should later use axis settings if needed)
param set-default CA_ROTOR12_PX  0.00
param set-default CA_ROTOR12_PY  0.00
param set-default CA_ROTOR12_KM  0.00

# Gazebo ESC function mapping
param set-default SIM_GZ_EC_FUNC1   101
param set-default SIM_GZ_EC_FUNC2   102
param set-default SIM_GZ_EC_FUNC3   103
param set-default SIM_GZ_EC_FUNC4   104
param set-default SIM_GZ_EC_FUNC5   105
param set-default SIM_GZ_EC_FUNC6   106
param set-default SIM_GZ_EC_FUNC7   107
param set-default SIM_GZ_EC_FUNC8   108
param set-default SIM_GZ_EC_FUNC9   109
param set-default SIM_GZ_EC_FUNC10  110
param set-default SIM_GZ_EC_FUNC11  111
param set-default SIM_GZ_EC_FUNC12  112
param set-default SIM_GZ_EC_FUNC13  113

# Gazebo ESC min/max
param set-default SIM_GZ_EC_MIN1    150
param set-default SIM_GZ_EC_MIN2    150
param set-default SIM_GZ_EC_MIN3    150
param set-default SIM_GZ_EC_MIN4    150
param set-default SIM_GZ_EC_MIN5    150
param set-default SIM_GZ_EC_MIN6    150
param set-default SIM_GZ_EC_MIN7    150
param set-default SIM_GZ_EC_MIN8    150
param set-default SIM_GZ_EC_MIN9    150
param set-default SIM_GZ_EC_MIN10   150
param set-default SIM_GZ_EC_MIN11   150
param set-default SIM_GZ_EC_MIN12   150
param set-default SIM_GZ_EC_MIN13   150

param set-default SIM_GZ_EC_MAX1    1000
param set-default SIM_GZ_EC_MAX2    1000
param set-default SIM_GZ_EC_MAX3    1000
param set-default SIM_GZ_EC_MAX4    1000
param set-default SIM_GZ_EC_MAX5    1000
param set-default SIM_GZ_EC_MAX6    1000
param set-default SIM_GZ_EC_MAX7    1000
param set-default SIM_GZ_EC_MAX8    1000
param set-default SIM_GZ_EC_MAX9    1000
param set-default SIM_GZ_EC_MAX10   1000
param set-default SIM_GZ_EC_MAX11   1000
param set-default SIM_GZ_EC_MAX12   1000
param set-default SIM_GZ_EC_MAX13   1000

param set-default MPC_THR_HOVER 0.60
param set-default NAV_DLL_ACT 2
