#!/bin/sh
#
# @name Gazebo teTra_mk-7_EM2
#
# @type Quadrotor
#

. ${R}etc/init.d/rc.vtol_defaults

PX4_SIMULATOR=${PX4_SIMULATOR:=gz}
PX4_GZ_WORLD=${PX4_GZ_WORLD:=default}
PX4_SIM_MODEL=${PX4_SIM_MODEL:=teTra_mk-7_EM2}

param set-default SIM_GZ_EN 1

param set-default SENS_EN_ARSPDSIM 1

# TODO: Enable motor failure detection when the
# VTOL no longer reports 0A for all ESCs in SITL
param set-default FD_ACT_EN 0
param set-default FD_ACT_MOT_TOUT 500

param set-default CA_AIRFRAME 22001
param set-default COM_PREARM_MODE 2


param set-default CA_ROTOR_COUNT 13

# ============================================
# Lift rotors (Rotor 0-11)
# ============================================

# Rotor 0-5: Lower configuration (Y-negative side)
param set-default CA_ROTOR0_PX   4.03
param set-default CA_ROTOR0_PY  -1.45
param set-default CA_ROTOR0_PZ  -0.93
param set-default CA_ROTOR0_KM  -0.05
param set-default CA_ROTOR0_AX   0.0
param set-default CA_ROTOR0_AY  -0.13
param set-default CA_ROTOR0_AZ  -0.99

param set-default CA_ROTOR1_PX   1.95
param set-default CA_ROTOR1_PY  -1.45
param set-default CA_ROTOR1_PZ  -0.93
param set-default CA_ROTOR1_KM   0.05
param set-default CA_ROTOR1_AX   0.0
param set-default CA_ROTOR1_AY   0.13
param set-default CA_ROTOR1_AZ  -0.99

param set-default CA_ROTOR2_PX   1.95
param set-default CA_ROTOR2_PY  -4.00
param set-default CA_ROTOR2_PZ  -0.93
param set-default CA_ROTOR2_KM  -0.05
param set-default CA_ROTOR2_AX   0.0
param set-default CA_ROTOR2_AY  -0.13
param set-default CA_ROTOR2_AZ  -0.99


param set-default CA_ROTOR3_PX  -1.95
param set-default CA_ROTOR3_PY  -4.00
param set-default CA_ROTOR3_PZ  -0.93
param set-default CA_ROTOR3_KM  -0.05
param set-default CA_ROTOR3_AX   0.0
param set-default CA_ROTOR3_AY   0.13
param set-default CA_ROTOR3_AZ  -0.99

param set-default CA_ROTOR4_PX  -1.95
param set-default CA_ROTOR4_PY  -1.45
param set-default CA_ROTOR4_PZ  -0.93
param set-default CA_ROTOR4_KM   0.05
param set-default CA_ROTOR4_AX   0.0
param set-default CA_ROTOR4_AY  -0.13
param set-default CA_ROTOR4_AZ  -0.99

param set-default CA_ROTOR5_PX  -4.03
param set-default CA_ROTOR5_PY  -1.45
param set-default CA_ROTOR5_PZ  -0.93
param set-default CA_ROTOR5_KM  -0.05
param set-default CA_ROTOR5_AX   0.0
param set-default CA_ROTOR5_AY   0.13
param set-default CA_ROTOR5_AZ  -0.99

# Rotor 6-11: Upper configuration (Y-positive side, Y-mirror symmetric)
param set-default CA_ROTOR6_PX  -4.03
param set-default CA_ROTOR6_PY   1.45
param set-default CA_ROTOR6_PZ  -0.93
param set-default CA_ROTOR6_KM   0.05
param set-default CA_ROTOR6_AX   0.0
param set-default CA_ROTOR6_AY  -0.13
param set-default CA_ROTOR6_AZ  -0.99

param set-default CA_ROTOR7_PX  -1.95
param set-default CA_ROTOR7_PY   1.45
param set-default CA_ROTOR7_PZ  -0.93
param set-default CA_ROTOR7_KM  -0.05
param set-default CA_ROTOR7_AX   0.0
param set-default CA_ROTOR7_AY   0.13
param set-default CA_ROTOR7_AZ  -0.99

param set-default CA_ROTOR8_PX  -1.95
param set-default CA_ROTOR8_PY   4.00
param set-default CA_ROTOR8_PZ  -0.93
param set-default CA_ROTOR8_KM   0.05
param set-default CA_ROTOR8_AX   0.0
param set-default CA_ROTOR8_AY  -0.13
param set-default CA_ROTOR8_AZ  -0.99

param set-default CA_ROTOR9_PX   1.95
param set-default CA_ROTOR9_PY   4.00
param set-default CA_ROTOR9_PZ  -0.93
param set-default CA_ROTOR9_KM   0.05
param set-default CA_ROTOR9_AX   0.0
param set-default CA_ROTOR9_AY   0.13
param set-default CA_ROTOR9_AZ  -0.99

param set-default CA_ROTOR10_PX  1.95
param set-default CA_ROTOR10_PY  1.45
param set-default CA_ROTOR10_PZ -0.93
param set-default CA_ROTOR10_KM -0.05
param set-default CA_ROTOR10_AX  0.0
param set-default CA_ROTOR10_AY -0.13
param set-default CA_ROTOR10_AZ -0.99

param set-default CA_ROTOR11_PX  4.03
param set-default CA_ROTOR11_PY  1.45
param set-default CA_ROTOR11_PZ -0.93
param set-default CA_ROTOR11_KM  0.05
param set-default CA_ROTOR11_AX  0.0
param set-default CA_ROTOR11_AY  0.13
param set-default CA_ROTOR11_AZ -0.99

# ============================================
# Cruise propeller (Rotor 12)
# ============================================
# Cruise prop (temporary example; forward prop should later use axis settings if needed)
param set-default CA_ROTOR12_PX -1.80
param set-default CA_ROTOR12_PY  0.00
param set-default CA_ROTOR12_PZ -0.45
param set-default CA_ROTOR12_KM  0.05
param set-default CA_ROTOR12_AX -1.0
param set-default CA_ROTOR12_AY  0.0
param set-default CA_ROTOR12_AZ  0.0

# ============================================
# Gazebo ESC Configuration
# ============================================

# ESC function mapping (mapping rotor outputs to ESC channels)
param set-default SIM_GZ_EC_FUNC1   101
param set-default SIM_GZ_EC_FUNC2   102
param set-default SIM_GZ_EC_FUNC3   103
param set-default SIM_GZ_EC_FUNC4   104
param set-default SIM_GZ_EC_FUNC5   105
param set-default SIM_GZ_EC_FUNC6   106
param set-default SIM_GZ_EC_FUNC7   107
param set-default SIM_GZ_EC_FUNC8   108
param set-default SIM_GZ_EC_FUNC9   109
param set-default SIM_GZ_EC_FUNC10  110
param set-default SIM_GZ_EC_FUNC11  111
param set-default SIM_GZ_EC_FUNC12  112
param set-default SIM_GZ_EC_FUNC13  113

# ESC PWM min/max values
# MIN: Minimum throttle value (1000 microseconds)
# MAX: Maximum throttle value (2000 microseconds)
param set-default SIM_GZ_EC_MIN1    150
param set-default SIM_GZ_EC_MIN2    150
param set-default SIM_GZ_EC_MIN3    150
param set-default SIM_GZ_EC_MIN4    150
param set-default SIM_GZ_EC_MIN5    150
param set-default SIM_GZ_EC_MIN6    150
param set-default SIM_GZ_EC_MIN7    150
param set-default SIM_GZ_EC_MIN8    150
param set-default SIM_GZ_EC_MIN9    150
param set-default SIM_GZ_EC_MIN10   150
param set-default SIM_GZ_EC_MIN11   150
param set-default SIM_GZ_EC_MIN12   150
param set-default SIM_GZ_EC_MIN13   150

param set-default SIM_GZ_EC_MAX1    1000
param set-default SIM_GZ_EC_MAX2    1000
param set-default SIM_GZ_EC_MAX3    1000
param set-default SIM_GZ_EC_MAX4    1000
param set-default SIM_GZ_EC_MAX5    1000
param set-default SIM_GZ_EC_MAX6    1000
param set-default SIM_GZ_EC_MAX7    1000
param set-default SIM_GZ_EC_MAX8    1000
param set-default SIM_GZ_EC_MAX9    1000
param set-default SIM_GZ_EC_MAX10   1000
param set-default SIM_GZ_EC_MAX11   1000
param set-default SIM_GZ_EC_MAX12   1000
param set-default SIM_GZ_EC_MAX13   1000

# ============================================
# Vehicle Configuration
# ============================================

# Multicopter hover thrust setting
param set-default MPC_THR_HOVER 0.60
param set-default NAV_ACC_RAD 5
param set-default NAV_DLL_ACT 2

# Servo (control surface) configuration
param set-default SIM_GZ_SV_FUNC1 201
param set-default SIM_GZ_SV_FUNC2 202
param set-default SIM_GZ_SV_FUNC3 203
param set-default SIM_GZ_SV_FUNC4 204
param set-default SIM_GZ_SV_FUNC5 205



param set-default COM_RC_IN_MODE 1

# Control surface allocation (elevator, ailerons)
param set-default CA_SV_CS_COUNT 5

param set-default CA_SV_CS0_TYPE 1
param set-default CA_SV_CS0_TRQ_R -0.5
param set-default CA_SV_CS1_TYPE 2
param set-default CA_SV_CS1_TRQ_R 0.5
param set-default CA_SV_CS2_TYPE 3
param set-default CA_SV_CS2_TRQ_P 1
param set-default CA_SV_CS3_TYPE 4
param set-default CA_SV_CS3_TRQ_Y 1
param set-default CA_SV_CS4_TYPE 4
param set-default CA_SV_CS4_TRQ_Y 1

# ============================================
# Flight Controller Tuning Parameters
# ============================================

# Fixed-wing control parameters
param set-default NPFG_PERIOD 12
param set-default FW_PR_FF 0.2
param set-default FW_PR_P 0.9
param set-default FW_PSP_OFF 2
param set-default FW_P_LIM_MIN -15
param set-default FW_RR_FF 0.1
param set-default FW_RR_P 0.3
param set-default FW_THR_TRIM 0.25
param set-default FW_THR_MAX 0.6
param set-default FW_THR_MIN 0.05
param set-default FW_T_CLMB_MAX 8
param set-default FW_T_SINK_MAX 2.7
param set-default FW_T_SINK_MIN 2.2

# Multicopter control parameters
param set-default MC_AIRMODE 1
param set-default MC_ROLLRATE_P 0.3
param set-default MC_YAW_P 1.6

# Mission and position control
param set-default MIS_TAKEOFF_ALT 10
param set-default MPC_XY_P 0.8
param set-default MPC_XY_VEL_P_ACC 3
param set-default MPC_XY_VEL_I_ACC 4
param set-default MPC_XY_VEL_D_ACC 0.1

# VTOL (Vertical Takeoff and Landing) configuration
param set-default VT_FWD_THRUST_EN 4
param set-default VT_PITCH_MIN -5
param set-default VT_F_TRANS_THR 1
param set-default VT_TYPE 2
